name: NanoPi R1S OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  OpenWrt-18_06:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Init Building Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell mysql* php* mssql-tools msodbcsql17 android*
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 coreutils gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python3-setuptools python-ply python3-ply haveged lrzsz device-tree-compiler scons antlr3 gperf ecj fastjar re2c xz-utils tar zip
        sudo -EH pip3 install -U pyrogram tgCrypto
        for i in $(ls /usr/bin/*-8); do sudo -E ln -sf $i ${i%%-8*}; done
        sudo -E ln -sf /usr/include/asm-generic /usr/include/asm
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E swapoff -a
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android /opt/ghc /swapfile
    - name: Clone Source
      run: |
        cd "/home/runner"
        git clone --branch "openwrt-18.06" --single-branch "https://github.com/immortalwrt/immortalwrt" "openwrt"
        sudo chown -R runner:runner "openwrt"
        cd "/home/runner/openwrt"
        ./scripts/feeds update -a
        ./scripts/feeds install -a
    - name: Build OpenWrt-18.06
      run: |
        cd "/home/runner/openwrt"
        cp -f "${GITHUB_WORKSPACE}/configs/1806-config.seed" ".config"
        chmod +x ${GITHUB_WORKSPACE}/scripts/customize.sh && ${GITHUB_WORKSPACE}/scripts/customize.sh
        make defconfig
        make -j$[$(nproc)+1]
        mv -f "bin/targets/sunxi/cortexa53/openwrt-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz" "../openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz"
        mv -f "bin/targets/sunxi/cortexa53/openwrt-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz" "../openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz"
        mv -f "bin/targets/sunxi/cortexa53/sha256sums" "../openwrt-18.06-sha256sums"
    - name: Rebuild OpenWrt-18.06 to Collect Error Log
      if: failure()
      run: |
        cd "/home/runner/openwrt"
        make -j1 V=s
        mv -f "bin/targets/sunxi/cortexa53/openwrt-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz" "../openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz"
        mv -f "bin/targets/sunxi/cortexa53/openwrt-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz" "../openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz"
        mv -f "bin/targets/sunxi/cortexa53/sha256sums" "../openwrt-18.06-sha256sums"
    - name: Upload OpenWrt-18.06 SHA256SUM Hash
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-18.06-sha256sums
        path: /home/runner/openwrt-18.06-sha256sums
    - name: Upload OpenWrt-18.06 EXT4 Firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz
        path: /home/runner/openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz
    - name: Upload OpenWrt-18.06 SquashFS Firmware
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz
        path: /home/runner/openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz
    #- name: Upload OpenWrt-18.06 Firmwares to Cloud
    #  timeout-minutes: 30
    #  run: |
    #    cd "/home/runner"
    #    zip -j "openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-sdcard.zip" "openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-ext4-sdcard.img.gz" "openwrt-18.06-sunxi-cortexa53-friendlyarm_nanopi-r1s-h5-squashfs-sdcard.img.gz" "openwrt-18.06-sha256sums"
    #    ${GITHUB_WORKSPACE}/scripts/upload_firmware.py  --device-name "FriendlyARM NanoPi R1S (H5)" --device-file "sunxi-cortexa53-friendlyarm_nanopi-r1s-h5" --openwrt-version "18.06" --kernel-version "4.19" --api-id "${{ secrets.TELEGRAM_API_ID }}" --api-hash "${{ secrets.TELEGRAM_API_HASH }}" --bot-token "${{ secrets.TELEGRAM_BOT_TOKEN }}" || exit 0
  Cleanup-Old-Artifacts:
    needs: OpenWrt-18_06
    runs-on: ubuntu-18.04
    steps:
    - name: Cleanup Old Action Artifacts
      uses: kolpav/purge-artifacts-action@v1
      with:
        token: ${{ github.token }}
        expire-in: 7d
  Cleanup-Workflow-Runs:
    needs: Cleanup-Old-Artifacts
    runs-on: ubuntu-18.04
    steps:
      - name: Cleanup Workflow Runs
        uses: GitRML/delete-workflow-runs@v1.2.1
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
